import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/sheard/Header/Header";
import Footer from "@/components/sheard/Footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "MD Kawsar Alam",
  description: "Generated by MD kawsar alam",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
   <head>
        <link rel="icon" href="kawsar.jpg" />
      </head>
      <body className={inter.className}>
        <Header />
        {children}
        <Footer/>
      </body>
    </html>
  );
}
